apiVersion: v1
kind: ConfigMap
metadata:
 name: aws-auth
 namespace: kube-system
data:
 mapRoles: |
   - rolearn: arn:aws:iam::526037358249:role/NodeGroup01-NodeInstanceRole-1FS8W27E4N9YG
     username: system:node:{{EC2PrivateDNSName}}
     groups:
       - system:bootstrappers
       - system:nodes



